os: linux
dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - sudo apt install libsfml-dev
  - mkdir build
  - cd build
  - cmake ../CMakeLists.txt
  - cd ../
  - make