# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mano/Documents/univ/Gevorderd Programmeren/space-invaders"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mano/Documents/univ/Gevorderd Programmeren/space-invaders"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/clion-2019.2.3/bin/cmake/linux/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mano/Documents/univ/Gevorderd Programmeren/space-invaders/CMakeFiles" "/home/mano/Documents/univ/Gevorderd Programmeren/space-invaders/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mano/Documents/univ/Gevorderd Programmeren/space-invaders/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named space_invaders

# Build rule for target.
space_invaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 space_invaders
.PHONY : space_invaders

# fast build rule for target.
space_invaders/fast:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/build
.PHONY : space_invaders/fast

src/entities/abstract_classes/View.o: src/entities/abstract_classes/View.cpp.o

.PHONY : src/entities/abstract_classes/View.o

# target to build an object file
src/entities/abstract_classes/View.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/abstract_classes/View.cpp.o
.PHONY : src/entities/abstract_classes/View.cpp.o

src/entities/abstract_classes/View.i: src/entities/abstract_classes/View.cpp.i

.PHONY : src/entities/abstract_classes/View.i

# target to preprocess a source file
src/entities/abstract_classes/View.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/abstract_classes/View.cpp.i
.PHONY : src/entities/abstract_classes/View.cpp.i

src/entities/abstract_classes/View.s: src/entities/abstract_classes/View.cpp.s

.PHONY : src/entities/abstract_classes/View.s

# target to generate assembly for a file
src/entities/abstract_classes/View.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/abstract_classes/View.cpp.s
.PHONY : src/entities/abstract_classes/View.cpp.s

src/entities/enemies/green_alien/GreenAlien.o: src/entities/enemies/green_alien/GreenAlien.cpp.o

.PHONY : src/entities/enemies/green_alien/GreenAlien.o

# target to build an object file
src/entities/enemies/green_alien/GreenAlien.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlien.cpp.o
.PHONY : src/entities/enemies/green_alien/GreenAlien.cpp.o

src/entities/enemies/green_alien/GreenAlien.i: src/entities/enemies/green_alien/GreenAlien.cpp.i

.PHONY : src/entities/enemies/green_alien/GreenAlien.i

# target to preprocess a source file
src/entities/enemies/green_alien/GreenAlien.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlien.cpp.i
.PHONY : src/entities/enemies/green_alien/GreenAlien.cpp.i

src/entities/enemies/green_alien/GreenAlien.s: src/entities/enemies/green_alien/GreenAlien.cpp.s

.PHONY : src/entities/enemies/green_alien/GreenAlien.s

# target to generate assembly for a file
src/entities/enemies/green_alien/GreenAlien.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlien.cpp.s
.PHONY : src/entities/enemies/green_alien/GreenAlien.cpp.s

src/entities/enemies/green_alien/GreenAlienController.o: src/entities/enemies/green_alien/GreenAlienController.cpp.o

.PHONY : src/entities/enemies/green_alien/GreenAlienController.o

# target to build an object file
src/entities/enemies/green_alien/GreenAlienController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienController.cpp.o
.PHONY : src/entities/enemies/green_alien/GreenAlienController.cpp.o

src/entities/enemies/green_alien/GreenAlienController.i: src/entities/enemies/green_alien/GreenAlienController.cpp.i

.PHONY : src/entities/enemies/green_alien/GreenAlienController.i

# target to preprocess a source file
src/entities/enemies/green_alien/GreenAlienController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienController.cpp.i
.PHONY : src/entities/enemies/green_alien/GreenAlienController.cpp.i

src/entities/enemies/green_alien/GreenAlienController.s: src/entities/enemies/green_alien/GreenAlienController.cpp.s

.PHONY : src/entities/enemies/green_alien/GreenAlienController.s

# target to generate assembly for a file
src/entities/enemies/green_alien/GreenAlienController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienController.cpp.s
.PHONY : src/entities/enemies/green_alien/GreenAlienController.cpp.s

src/entities/enemies/green_alien/GreenAlienView.o: src/entities/enemies/green_alien/GreenAlienView.cpp.o

.PHONY : src/entities/enemies/green_alien/GreenAlienView.o

# target to build an object file
src/entities/enemies/green_alien/GreenAlienView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienView.cpp.o
.PHONY : src/entities/enemies/green_alien/GreenAlienView.cpp.o

src/entities/enemies/green_alien/GreenAlienView.i: src/entities/enemies/green_alien/GreenAlienView.cpp.i

.PHONY : src/entities/enemies/green_alien/GreenAlienView.i

# target to preprocess a source file
src/entities/enemies/green_alien/GreenAlienView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienView.cpp.i
.PHONY : src/entities/enemies/green_alien/GreenAlienView.cpp.i

src/entities/enemies/green_alien/GreenAlienView.s: src/entities/enemies/green_alien/GreenAlienView.cpp.s

.PHONY : src/entities/enemies/green_alien/GreenAlienView.s

# target to generate assembly for a file
src/entities/enemies/green_alien/GreenAlienView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/green_alien/GreenAlienView.cpp.s
.PHONY : src/entities/enemies/green_alien/GreenAlienView.cpp.s

src/entities/enemies/purple_alien/PurpleAlien.o: src/entities/enemies/purple_alien/PurpleAlien.cpp.o

.PHONY : src/entities/enemies/purple_alien/PurpleAlien.o

# target to build an object file
src/entities/enemies/purple_alien/PurpleAlien.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlien.cpp.o
.PHONY : src/entities/enemies/purple_alien/PurpleAlien.cpp.o

src/entities/enemies/purple_alien/PurpleAlien.i: src/entities/enemies/purple_alien/PurpleAlien.cpp.i

.PHONY : src/entities/enemies/purple_alien/PurpleAlien.i

# target to preprocess a source file
src/entities/enemies/purple_alien/PurpleAlien.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlien.cpp.i
.PHONY : src/entities/enemies/purple_alien/PurpleAlien.cpp.i

src/entities/enemies/purple_alien/PurpleAlien.s: src/entities/enemies/purple_alien/PurpleAlien.cpp.s

.PHONY : src/entities/enemies/purple_alien/PurpleAlien.s

# target to generate assembly for a file
src/entities/enemies/purple_alien/PurpleAlien.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlien.cpp.s
.PHONY : src/entities/enemies/purple_alien/PurpleAlien.cpp.s

src/entities/enemies/purple_alien/PurpleAlienController.o: src/entities/enemies/purple_alien/PurpleAlienController.cpp.o

.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.o

# target to build an object file
src/entities/enemies/purple_alien/PurpleAlienController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienController.cpp.o
.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.cpp.o

src/entities/enemies/purple_alien/PurpleAlienController.i: src/entities/enemies/purple_alien/PurpleAlienController.cpp.i

.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.i

# target to preprocess a source file
src/entities/enemies/purple_alien/PurpleAlienController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienController.cpp.i
.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.cpp.i

src/entities/enemies/purple_alien/PurpleAlienController.s: src/entities/enemies/purple_alien/PurpleAlienController.cpp.s

.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.s

# target to generate assembly for a file
src/entities/enemies/purple_alien/PurpleAlienController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienController.cpp.s
.PHONY : src/entities/enemies/purple_alien/PurpleAlienController.cpp.s

src/entities/enemies/purple_alien/PurpleAlienView.o: src/entities/enemies/purple_alien/PurpleAlienView.cpp.o

.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.o

# target to build an object file
src/entities/enemies/purple_alien/PurpleAlienView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienView.cpp.o
.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.cpp.o

src/entities/enemies/purple_alien/PurpleAlienView.i: src/entities/enemies/purple_alien/PurpleAlienView.cpp.i

.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.i

# target to preprocess a source file
src/entities/enemies/purple_alien/PurpleAlienView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienView.cpp.i
.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.cpp.i

src/entities/enemies/purple_alien/PurpleAlienView.s: src/entities/enemies/purple_alien/PurpleAlienView.cpp.s

.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.s

# target to generate assembly for a file
src/entities/enemies/purple_alien/PurpleAlienView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/purple_alien/PurpleAlienView.cpp.s
.PHONY : src/entities/enemies/purple_alien/PurpleAlienView.cpp.s

src/entities/enemies/red_alien/RedAlien.o: src/entities/enemies/red_alien/RedAlien.cpp.o

.PHONY : src/entities/enemies/red_alien/RedAlien.o

# target to build an object file
src/entities/enemies/red_alien/RedAlien.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlien.cpp.o
.PHONY : src/entities/enemies/red_alien/RedAlien.cpp.o

src/entities/enemies/red_alien/RedAlien.i: src/entities/enemies/red_alien/RedAlien.cpp.i

.PHONY : src/entities/enemies/red_alien/RedAlien.i

# target to preprocess a source file
src/entities/enemies/red_alien/RedAlien.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlien.cpp.i
.PHONY : src/entities/enemies/red_alien/RedAlien.cpp.i

src/entities/enemies/red_alien/RedAlien.s: src/entities/enemies/red_alien/RedAlien.cpp.s

.PHONY : src/entities/enemies/red_alien/RedAlien.s

# target to generate assembly for a file
src/entities/enemies/red_alien/RedAlien.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlien.cpp.s
.PHONY : src/entities/enemies/red_alien/RedAlien.cpp.s

src/entities/enemies/red_alien/RedAlienController.o: src/entities/enemies/red_alien/RedAlienController.cpp.o

.PHONY : src/entities/enemies/red_alien/RedAlienController.o

# target to build an object file
src/entities/enemies/red_alien/RedAlienController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienController.cpp.o
.PHONY : src/entities/enemies/red_alien/RedAlienController.cpp.o

src/entities/enemies/red_alien/RedAlienController.i: src/entities/enemies/red_alien/RedAlienController.cpp.i

.PHONY : src/entities/enemies/red_alien/RedAlienController.i

# target to preprocess a source file
src/entities/enemies/red_alien/RedAlienController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienController.cpp.i
.PHONY : src/entities/enemies/red_alien/RedAlienController.cpp.i

src/entities/enemies/red_alien/RedAlienController.s: src/entities/enemies/red_alien/RedAlienController.cpp.s

.PHONY : src/entities/enemies/red_alien/RedAlienController.s

# target to generate assembly for a file
src/entities/enemies/red_alien/RedAlienController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienController.cpp.s
.PHONY : src/entities/enemies/red_alien/RedAlienController.cpp.s

src/entities/enemies/red_alien/RedAlienView.o: src/entities/enemies/red_alien/RedAlienView.cpp.o

.PHONY : src/entities/enemies/red_alien/RedAlienView.o

# target to build an object file
src/entities/enemies/red_alien/RedAlienView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienView.cpp.o
.PHONY : src/entities/enemies/red_alien/RedAlienView.cpp.o

src/entities/enemies/red_alien/RedAlienView.i: src/entities/enemies/red_alien/RedAlienView.cpp.i

.PHONY : src/entities/enemies/red_alien/RedAlienView.i

# target to preprocess a source file
src/entities/enemies/red_alien/RedAlienView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienView.cpp.i
.PHONY : src/entities/enemies/red_alien/RedAlienView.cpp.i

src/entities/enemies/red_alien/RedAlienView.s: src/entities/enemies/red_alien/RedAlienView.cpp.s

.PHONY : src/entities/enemies/red_alien/RedAlienView.s

# target to generate assembly for a file
src/entities/enemies/red_alien/RedAlienView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/enemies/red_alien/RedAlienView.cpp.s
.PHONY : src/entities/enemies/red_alien/RedAlienView.cpp.s

src/entities/playership/PlayerShip.o: src/entities/playership/PlayerShip.cpp.o

.PHONY : src/entities/playership/PlayerShip.o

# target to build an object file
src/entities/playership/PlayerShip.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShip.cpp.o
.PHONY : src/entities/playership/PlayerShip.cpp.o

src/entities/playership/PlayerShip.i: src/entities/playership/PlayerShip.cpp.i

.PHONY : src/entities/playership/PlayerShip.i

# target to preprocess a source file
src/entities/playership/PlayerShip.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShip.cpp.i
.PHONY : src/entities/playership/PlayerShip.cpp.i

src/entities/playership/PlayerShip.s: src/entities/playership/PlayerShip.cpp.s

.PHONY : src/entities/playership/PlayerShip.s

# target to generate assembly for a file
src/entities/playership/PlayerShip.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShip.cpp.s
.PHONY : src/entities/playership/PlayerShip.cpp.s

src/entities/playership/PlayerShipController.o: src/entities/playership/PlayerShipController.cpp.o

.PHONY : src/entities/playership/PlayerShipController.o

# target to build an object file
src/entities/playership/PlayerShipController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipController.cpp.o
.PHONY : src/entities/playership/PlayerShipController.cpp.o

src/entities/playership/PlayerShipController.i: src/entities/playership/PlayerShipController.cpp.i

.PHONY : src/entities/playership/PlayerShipController.i

# target to preprocess a source file
src/entities/playership/PlayerShipController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipController.cpp.i
.PHONY : src/entities/playership/PlayerShipController.cpp.i

src/entities/playership/PlayerShipController.s: src/entities/playership/PlayerShipController.cpp.s

.PHONY : src/entities/playership/PlayerShipController.s

# target to generate assembly for a file
src/entities/playership/PlayerShipController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipController.cpp.s
.PHONY : src/entities/playership/PlayerShipController.cpp.s

src/entities/playership/PlayerShipView.o: src/entities/playership/PlayerShipView.cpp.o

.PHONY : src/entities/playership/PlayerShipView.o

# target to build an object file
src/entities/playership/PlayerShipView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipView.cpp.o
.PHONY : src/entities/playership/PlayerShipView.cpp.o

src/entities/playership/PlayerShipView.i: src/entities/playership/PlayerShipView.cpp.i

.PHONY : src/entities/playership/PlayerShipView.i

# target to preprocess a source file
src/entities/playership/PlayerShipView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipView.cpp.i
.PHONY : src/entities/playership/PlayerShipView.cpp.i

src/entities/playership/PlayerShipView.s: src/entities/playership/PlayerShipView.cpp.s

.PHONY : src/entities/playership/PlayerShipView.s

# target to generate assembly for a file
src/entities/playership/PlayerShipView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/playership/PlayerShipView.cpp.s
.PHONY : src/entities/playership/PlayerShipView.cpp.s

src/entities/projectiles/ProjectileFactory.o: src/entities/projectiles/ProjectileFactory.cpp.o

.PHONY : src/entities/projectiles/ProjectileFactory.o

# target to build an object file
src/entities/projectiles/ProjectileFactory.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/ProjectileFactory.cpp.o
.PHONY : src/entities/projectiles/ProjectileFactory.cpp.o

src/entities/projectiles/ProjectileFactory.i: src/entities/projectiles/ProjectileFactory.cpp.i

.PHONY : src/entities/projectiles/ProjectileFactory.i

# target to preprocess a source file
src/entities/projectiles/ProjectileFactory.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/ProjectileFactory.cpp.i
.PHONY : src/entities/projectiles/ProjectileFactory.cpp.i

src/entities/projectiles/ProjectileFactory.s: src/entities/projectiles/ProjectileFactory.cpp.s

.PHONY : src/entities/projectiles/ProjectileFactory.s

# target to generate assembly for a file
src/entities/projectiles/ProjectileFactory.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/ProjectileFactory.cpp.s
.PHONY : src/entities/projectiles/ProjectileFactory.cpp.s

src/entities/projectiles/standard/StandardProjectile.o: src/entities/projectiles/standard/StandardProjectile.cpp.o

.PHONY : src/entities/projectiles/standard/StandardProjectile.o

# target to build an object file
src/entities/projectiles/standard/StandardProjectile.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectile.cpp.o
.PHONY : src/entities/projectiles/standard/StandardProjectile.cpp.o

src/entities/projectiles/standard/StandardProjectile.i: src/entities/projectiles/standard/StandardProjectile.cpp.i

.PHONY : src/entities/projectiles/standard/StandardProjectile.i

# target to preprocess a source file
src/entities/projectiles/standard/StandardProjectile.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectile.cpp.i
.PHONY : src/entities/projectiles/standard/StandardProjectile.cpp.i

src/entities/projectiles/standard/StandardProjectile.s: src/entities/projectiles/standard/StandardProjectile.cpp.s

.PHONY : src/entities/projectiles/standard/StandardProjectile.s

# target to generate assembly for a file
src/entities/projectiles/standard/StandardProjectile.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectile.cpp.s
.PHONY : src/entities/projectiles/standard/StandardProjectile.cpp.s

src/entities/projectiles/standard/StandardProjectileController.o: src/entities/projectiles/standard/StandardProjectileController.cpp.o

.PHONY : src/entities/projectiles/standard/StandardProjectileController.o

# target to build an object file
src/entities/projectiles/standard/StandardProjectileController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileController.cpp.o
.PHONY : src/entities/projectiles/standard/StandardProjectileController.cpp.o

src/entities/projectiles/standard/StandardProjectileController.i: src/entities/projectiles/standard/StandardProjectileController.cpp.i

.PHONY : src/entities/projectiles/standard/StandardProjectileController.i

# target to preprocess a source file
src/entities/projectiles/standard/StandardProjectileController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileController.cpp.i
.PHONY : src/entities/projectiles/standard/StandardProjectileController.cpp.i

src/entities/projectiles/standard/StandardProjectileController.s: src/entities/projectiles/standard/StandardProjectileController.cpp.s

.PHONY : src/entities/projectiles/standard/StandardProjectileController.s

# target to generate assembly for a file
src/entities/projectiles/standard/StandardProjectileController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileController.cpp.s
.PHONY : src/entities/projectiles/standard/StandardProjectileController.cpp.s

src/entities/projectiles/standard/StandardProjectileView.o: src/entities/projectiles/standard/StandardProjectileView.cpp.o

.PHONY : src/entities/projectiles/standard/StandardProjectileView.o

# target to build an object file
src/entities/projectiles/standard/StandardProjectileView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileView.cpp.o
.PHONY : src/entities/projectiles/standard/StandardProjectileView.cpp.o

src/entities/projectiles/standard/StandardProjectileView.i: src/entities/projectiles/standard/StandardProjectileView.cpp.i

.PHONY : src/entities/projectiles/standard/StandardProjectileView.i

# target to preprocess a source file
src/entities/projectiles/standard/StandardProjectileView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileView.cpp.i
.PHONY : src/entities/projectiles/standard/StandardProjectileView.cpp.i

src/entities/projectiles/standard/StandardProjectileView.s: src/entities/projectiles/standard/StandardProjectileView.cpp.s

.PHONY : src/entities/projectiles/standard/StandardProjectileView.s

# target to generate assembly for a file
src/entities/projectiles/standard/StandardProjectileView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard/StandardProjectileView.cpp.s
.PHONY : src/entities/projectiles/standard/StandardProjectileView.cpp.s

src/entities/projectiles/standard_enemy/StandardEnemyProjectile.o: src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.o

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.o

# target to build an object file
src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.o
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.o

src/entities/projectiles/standard_enemy/StandardEnemyProjectile.i: src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.i

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.i

# target to preprocess a source file
src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.i
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.i

src/entities/projectiles/standard_enemy/StandardEnemyProjectile.s: src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.s

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.s

# target to generate assembly for a file
src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.s
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectile.cpp.s

src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.o: src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.o

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.o

# target to build an object file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.o
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.o

src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.i: src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.i

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.i

# target to preprocess a source file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.i
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.i

src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.s: src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.s

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.s

# target to generate assembly for a file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.s
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.cpp.s

src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.o: src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.o

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.o

# target to build an object file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.o
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.o

src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.i: src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.i

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.i

# target to preprocess a source file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.i
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.i

src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.s: src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.s

.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.s

# target to generate assembly for a file
src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.s
.PHONY : src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.cpp.s

src/game/Game.o: src/game/Game.cpp.o

.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i

.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s

.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/game/LevelLoader.o: src/game/LevelLoader.cpp.o

.PHONY : src/game/LevelLoader.o

# target to build an object file
src/game/LevelLoader.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/LevelLoader.cpp.o
.PHONY : src/game/LevelLoader.cpp.o

src/game/LevelLoader.i: src/game/LevelLoader.cpp.i

.PHONY : src/game/LevelLoader.i

# target to preprocess a source file
src/game/LevelLoader.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/LevelLoader.cpp.i
.PHONY : src/game/LevelLoader.cpp.i

src/game/LevelLoader.s: src/game/LevelLoader.cpp.s

.PHONY : src/game/LevelLoader.s

# target to generate assembly for a file
src/game/LevelLoader.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/game/LevelLoader.cpp.s
.PHONY : src/game/LevelLoader.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... space_invaders"
	@echo "... edit_cache"
	@echo "... src/entities/abstract_classes/View.o"
	@echo "... src/entities/abstract_classes/View.i"
	@echo "... src/entities/abstract_classes/View.s"
	@echo "... src/entities/enemies/green_alien/GreenAlien.o"
	@echo "... src/entities/enemies/green_alien/GreenAlien.i"
	@echo "... src/entities/enemies/green_alien/GreenAlien.s"
	@echo "... src/entities/enemies/green_alien/GreenAlienController.o"
	@echo "... src/entities/enemies/green_alien/GreenAlienController.i"
	@echo "... src/entities/enemies/green_alien/GreenAlienController.s"
	@echo "... src/entities/enemies/green_alien/GreenAlienView.o"
	@echo "... src/entities/enemies/green_alien/GreenAlienView.i"
	@echo "... src/entities/enemies/green_alien/GreenAlienView.s"
	@echo "... src/entities/enemies/purple_alien/PurpleAlien.o"
	@echo "... src/entities/enemies/purple_alien/PurpleAlien.i"
	@echo "... src/entities/enemies/purple_alien/PurpleAlien.s"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienController.o"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienController.i"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienController.s"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienView.o"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienView.i"
	@echo "... src/entities/enemies/purple_alien/PurpleAlienView.s"
	@echo "... src/entities/enemies/red_alien/RedAlien.o"
	@echo "... src/entities/enemies/red_alien/RedAlien.i"
	@echo "... src/entities/enemies/red_alien/RedAlien.s"
	@echo "... src/entities/enemies/red_alien/RedAlienController.o"
	@echo "... src/entities/enemies/red_alien/RedAlienController.i"
	@echo "... src/entities/enemies/red_alien/RedAlienController.s"
	@echo "... src/entities/enemies/red_alien/RedAlienView.o"
	@echo "... src/entities/enemies/red_alien/RedAlienView.i"
	@echo "... src/entities/enemies/red_alien/RedAlienView.s"
	@echo "... src/entities/playership/PlayerShip.o"
	@echo "... src/entities/playership/PlayerShip.i"
	@echo "... src/entities/playership/PlayerShip.s"
	@echo "... src/entities/playership/PlayerShipController.o"
	@echo "... src/entities/playership/PlayerShipController.i"
	@echo "... src/entities/playership/PlayerShipController.s"
	@echo "... src/entities/playership/PlayerShipView.o"
	@echo "... src/entities/playership/PlayerShipView.i"
	@echo "... src/entities/playership/PlayerShipView.s"
	@echo "... src/entities/projectiles/ProjectileFactory.o"
	@echo "... src/entities/projectiles/ProjectileFactory.i"
	@echo "... src/entities/projectiles/ProjectileFactory.s"
	@echo "... src/entities/projectiles/standard/StandardProjectile.o"
	@echo "... src/entities/projectiles/standard/StandardProjectile.i"
	@echo "... src/entities/projectiles/standard/StandardProjectile.s"
	@echo "... src/entities/projectiles/standard/StandardProjectileController.o"
	@echo "... src/entities/projectiles/standard/StandardProjectileController.i"
	@echo "... src/entities/projectiles/standard/StandardProjectileController.s"
	@echo "... src/entities/projectiles/standard/StandardProjectileView.o"
	@echo "... src/entities/projectiles/standard/StandardProjectileView.i"
	@echo "... src/entities/projectiles/standard/StandardProjectileView.s"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectile.o"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectile.i"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectile.s"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.o"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.i"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileController.s"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.o"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.i"
	@echo "... src/entities/projectiles/standard_enemy/StandardEnemyProjectileView.s"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/game/LevelLoader.o"
	@echo "... src/game/LevelLoader.i"
	@echo "... src/game/LevelLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

